- name: Create project dir
  file:
    path: /opt/web-stack
    state: directory

- name: Copy project files
  copy:
    src: "{{ item }}"
    dest: /opt/web-stack/
  loop:
    - docker-compose.yml
    - nginx
    - prometheus

- name: Run stack
  command: docker compose up -d
  args:
    chdir: /opt/web-stack
